/* 
    ESTE SCRIPT CRIA A TABELA PARTIDO E INSERE OS DADOS DE TODOS OS PARTIDO 
    REGISTRADOS NO TSE    
*/

USE gastos_parlamentares_db;

-- TABELA PARTIDO

DROP TABLE IF EXISTS partido;

CREATE TABLE partido (
	id INT,
	nome VARCHAR(255) NOT NULL,
	sigla VARCHAR(255) NOT NULL
);

ALTER TABLE partido MODIFY id INT AUTO_INCREMENT PRIMARY KEY;

-- DADOS INSERIDOS

INSERT INTO partido(nome, sigla) VALUES("MOVIMENTO DEMOCRÁTICO BRASILEIRO", "PMDB");
INSERT INTO partido(nome, sigla) VALUES("MOVIMENTO DEMOCRÁTICO BRASILEIRO", "MDB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO TRABALHISTA BRASILEIRO", "PTB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DEMOCRÁTICO TRABALHISTA", "PDT");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DOS TRABALHADORES", "PT");
INSERT INTO partido(nome, sigla) VALUES("DEMOCRATAS", "DEM");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO COMUNISTA DO BRASIL", "PCdoB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIALISTA BRASILEIRO", "PSB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA", "PSDB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO TRABALHISTA CRISTÃO", "PTC");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIAL CRISTÃO", "PSC");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DA MOBILIZAÇÃO NACIONAL", "PMN");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO REPUBLICANO PROGRESSISTA", "PRP");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO POPULAR SOCIALISTA", "PPS");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO VERDE	", "PV");
INSERT INTO partido(nome, sigla) VALUES("AVANTE", "AVANTE");
INSERT INTO partido(nome, sigla) VALUES("PROGRESSISTAS", "PP");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO", "PSTU");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO COMUNISTA BRASILEIRO", "PCB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO RENOVADOR TRABALHISTA BRASILEIRO", "PRTB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO HUMANISTA DA SOLIDARIEDADE", "PHS");
INSERT INTO partido(nome, sigla) VALUES("DEMOCRACIA CRISTÃ", "DC");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DA CAUSA OPERÁRIA", "PCO");
INSERT INTO partido(nome, sigla) VALUES("PODEMOS", "PODE");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIAL LIBERAL", "PSL");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO REPUBLICANO BRASILEIRO", "PRB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIALISMO E LIBERDADE", "PSOL");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DA REPÚBLICA", "PR");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO SOCIAL DEMOCRÁTICO", "PSD");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO PÁTRIA LIVRE", "PPL");
INSERT INTO partido(nome, sigla) VALUES("PATRIOTA", "PATRI");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO REPUBLICANO DA ORDEM SOCIAL", "PROS");
INSERT INTO partido(nome, sigla) VALUES("SOLIDARIEDADE", "SOLIDARIEDADE");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO NOVO", "NOVO");
INSERT INTO partido(nome, sigla) VALUES("REDE SUSTENTABILIDADE", "REDE");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO DA MULHER BRASILEIRA", "PMB");
INSERT INTO partido(nome, sigla) VALUES("PARTIDO NÃO INDENTIFICADO NO PORTAL DA TRANSPARENCI", "PNIPT");
